import type { ExecuteJobResult, ValidationResult } from "../../../runtime/offeringTypes.js";

async function getDexScreenerData(token: string) {
  try {
    const res = await fetch(`https://api.dexscreener.com/latest/dex/search?q=${token}`);
    const data = await res.json() as any;
    // Get first result that matches best
    return data.pairs?.[0] || null;
  } catch (e) {
    return null;
  }
}

export async function executeJob(request: any): Promise<ExecuteJobResult> {
  const token = request.token;
  const network = request.network || "base";

  console.log(`[token_inspector] Inspecting ${token} on ${network}`);

  const pair = await getDexScreenerData(token);
  if (!pair) {
    return { deliverable: `Error: Could not find token ${token} on DexScreener. Please verify the ticker or contract address.` };
  }

  const deliverable = `
# 🔎 Token Report: ${pair.baseToken.name} (${pair.baseToken.symbol})
**Network:** ${pair.chainId.toUpperCase()}
**DEX:** ${pair.dexId}

## 📊 Market Data
- **Current Price**: $${pair.priceUsd}
- **Market Cap**: $${pair.fdv?.toLocaleString() || "N/A"}
- **24h Volume**: $${pair.volume?.h24?.toLocaleString() || "N/A"}
- **Liquidity**: $${pair.liquidity?.usd?.toLocaleString() || "N/A"}

## 📈 Price Change
- **1h**: ${pair.priceChange?.h1}% 
- **6h**: ${pair.priceChange?.h6}%
- **24h**: ${pair.priceChange?.h24}%

## 🔗 Links
- **Contract Address**: \`${pair.baseToken.address}\`
- **DexScreener**: [View Chart](${pair.url})
- **Pair Address**: \`${pair.pairAddress}\`

*Report generated by Daedalus AI.*
  `.trim();

  return { deliverable };
}

export function validateRequirements(request: any): ValidationResult {
  if (!request.token) return { valid: false, reason: "A 'token' ticker or address is required." };
  return { valid: true };
}

export function requestPayment(request: any): string {
  return `Inspecting token ${request.token}...`;
}
