import type { ExecuteJobResult, ValidationResult } from "../../../runtime/offeringTypes.js";

async function getDexScreenerData(token: string) {
  try {
    // 1. If it looks like an EVM address (0x...) or Solana address (typically 32-44 base58 chars)
    const isAddress = token.startsWith("0x") || token.length >= 32;
    
    if (isAddress) {
      // Use the specific token endpoint for higher precision
      const res = await fetch(`https://api.dexscreener.com/latest/dex/tokens/${token}`);
      const data = await res.json() as any;
      if (data.pairs && data.pairs.length > 0) {
        // Return the pair with the highest liquidity
        return data.pairs.sort((a: any, b: any) => (b.liquidity?.usd || 0) - (a.liquidity?.usd || 0))[0];
      }
    }

    // 2. Fallback or ticker search
    const cleanToken = token.startsWith("$") ? token.substring(1) : token;
    const res = await fetch(`https://api.dexscreener.com/latest/dex/search?q=${cleanToken}`);
    const data = await res.json() as any;
    return data.pairs?.[0] || null;
  } catch (e) {
    return null;
  }
}

export async function executeJob(request: any): Promise<ExecuteJobResult> {
  const token = request.token.trim();
  const network = request.network || "base";

  console.log(`[token_inspector] Ingenious Inspecting ${token} on ${network}`);

  const pair = await getDexScreenerData(token);
  if (!pair) {
    return { deliverable: `Error: Could not find token data for "${token}" on DexScreener. \n\n💡 Tip: Please use the **Contract Address** (0x...) instead of the ticker for guaranteed results.` };
  }

  const deliverable = `
# 🔎 Token Report: ${pair.baseToken.name} (${pair.baseToken.symbol})
**Network:** ${pair.chainId.toUpperCase()}
**DEX:** ${pair.dexId}

## 📊 Market Data
- **Current Price**: $${pair.priceUsd}
- **Market Cap**: $${pair.fdv?.toLocaleString() || "N/A"}
- **24h Volume**: $${pair.volume?.h24?.toLocaleString() || "N/A"}
- **Liquidity**: $${pair.liquidity?.usd?.toLocaleString() || "N/A"}

## 📈 Price Change
- **1h**: ${pair.priceChange?.h1}% 
- **6h**: ${pair.priceChange?.h6}%
- **24h**: ${pair.priceChange?.h24}%

## 🔗 Links
- **Contract Address**: \`${pair.baseToken.address}\`
- **DexScreener**: [View Chart](${pair.url})
- **Pair Address**: \`${pair.pairAddress}\`

*Report generated by Daedalus AI.*
  `.trim();

  return { deliverable };
}

export function validateRequirements(request: any): ValidationResult {
  if (!request.token) return { valid: false, reason: "A token contract address (preferred) or ticker is required." };
  return { valid: true };
}

export function requestPayment(request: any): string {
  return `Inspecting token ${request.token}...`;
}
